version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${LOCAL_HTTP_PORT}:${HTTP_PORT}
    volumes:
      - ./.bin/:/root/
      - ./config/:/root/config/
      - ./.env:/root/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-bionic
    volumes:
      - ./.data/mongo:/data/db
    env_file:
      - .env
    ports:
      - ${LOCAL_MONGO_PORT}:${MONGO_PORT}
