name: Linter & Tests

on:
  push:
    brances:
      - '**'
  pull_request:
    breances:
      - '**'

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: golangci-link
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: install golang
        uses: actions/setup-go@v2
        with:
          version: 1.16

      - name: checout code
        uses: actions/checkout@v2

      - name: unit tests
        run: go test ./...
